# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cidocker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ab33de980a6245aa917ccc2b96309255 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_69f98e1b5d69433b99e24018e4890e73 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ab33de980a6245aa917ccc2b96309255 }}/amir732/mytestapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cidocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e813a9aa394e40b28852acddfb268b95 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ab33de980a6245aa917ccc2b96309255 }}/amir732/mytestapi:${{ github.sha }}'